#REST
rest :
  type : rest
  resource : "routing_rest.yml"
  prefix : /api

gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

api_login_check:
    path: /api/login_check

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /api

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
