<?php

namespace Kayneth\CreationBundle\Repository;

/**
 * CreationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreationRepository extends \Doctrine\ORM\EntityRepository
{
}
